title: Christopher
logo: https://github.com/cjoshreid/cjoshreid.github.io/blob/main/docs/unnamed.png?raw=true
#description:
theme: jekyll-theme-minimal 

<html>
<head>
<style>
body {
  background-image: url('{{ site.baseurl }}/webfonts/background.jpg');
}
</style>
</head>

</html>
